<a href="https://colab.research.google.com/github/MohneetKaur/Computer-Vision-with-Python-and-Tensorflow/blob/main/Tensor_Basics.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [1]:
import tensorflow as tf

In [2]:
tensor_zero_d = tf.constant(4)
print(tensor_zero_d)

tf.Tensor(4, shape=(), dtype=int32)


In [3]:
tensor_one_d = tf.constant([2,0,-3],dtype=tf.float32)
casted_tensor_one_d = tf.cast(tensor_one_d,dtype=tf.int16)
print(tensor_one_d)
print(casted_tensor_one_d)

tf.Tensor([ 2.  0. -3.], shape=(3,), dtype=float32)
tf.Tensor([ 2  0 -3], shape=(3,), dtype=int16)


In [4]:
tensor_string = tf.constant(["Hello World","hi"])
print(tensor_string)

tf.Tensor([b'Hello World' b'hi'], shape=(2,), dtype=string)


In [5]:
tensor_two_d = tf.constant([
    [1,2,0],
    [3,5,-1],
    [1,5,6],
    [2,3,8]
])

print(tensor_two_d)

tf.Tensor(
[[ 1  2  0]
 [ 3  5 -1]
 [ 1  5  6]
 [ 2  3  8]], shape=(4, 3), dtype=int32)


In [6]:
print(tensor_two_d.shape)

(4, 3)


In [7]:
tensor_three_d = tf.constant([
    [[2,0,1],
     [3,-4,7]],

    [[3,9,10],
     [7,10,4]],

    [[3,0,14],
     [10,1,0]]
])

print(tensor_three_d)

tf.Tensor(
[[[ 2  0  1]
  [ 3 -4  7]]

 [[ 3  9 10]
  [ 7 10  4]]

 [[ 3  0 14]
  [10  1  0]]], shape=(3, 2, 3), dtype=int32)


In [8]:
 print(tensor_three_d.shape)

(3, 2, 3)


In [9]:
tensor_four_d = tf.constant([
        [[[2,0,1],
         [3,-4,7]],

           [[3,9,10],
            [7,10,4]],

              [[3,0,14],
               [10,1,0]]],

                 [
                     [[3,2,11],
                      [7,6,10]],

                        [[-1,-7,-9],
                         [11,99,2]],

                           [[2,9,11],
                            [11,2,1]],
                     ]
])

print(tensor_four_d)

tf.Tensor(
[[[[ 2  0  1]
   [ 3 -4  7]]

  [[ 3  9 10]
   [ 7 10  4]]

  [[ 3  0 14]
   [10  1  0]]]


 [[[ 3  2 11]
   [ 7  6 10]]

  [[-1 -7 -9]
   [11 99  2]]

  [[ 2  9 11]
   [11  2  1]]]], shape=(2, 3, 2, 3), dtype=int32)


In [10]:
print(tensor_four_d.shape)

(2, 3, 2, 3)


In [11]:
import numpy as np

In [12]:
np_array = np.array([1,2,4])
print(np_array)

[1 2 4]


In [13]:
converted_tensor = tf.convert_to_tensor(np_array)
print(converted_tensor)

tf.Tensor([1 2 4], shape=(3,), dtype=int64)


In [14]:
eye_tensor = tf.eye(
    num_rows = 5,
    num_columns = 5,
    batch_shape = [3,],
    dtype = tf.dtypes.float32,
    name=None
)

print(eye_tensor)

tf.Tensor(
[[[1. 0. 0. 0. 0.]
  [0. 1. 0. 0. 0.]
  [0. 0. 1. 0. 0.]
  [0. 0. 0. 1. 0.]
  [0. 0. 0. 0. 1.]]

 [[1. 0. 0. 0. 0.]
  [0. 1. 0. 0. 0.]
  [0. 0. 1. 0. 0.]
  [0. 0. 0. 1. 0.]
  [0. 0. 0. 0. 1.]]

 [[1. 0. 0. 0. 0.]
  [0. 1. 0. 0. 0.]
  [0. 0. 1. 0. 0.]
  [0. 0. 0. 1. 0.]
  [0. 0. 0. 0. 1.]]], shape=(3, 5, 5), dtype=float32)


In [15]:
fill_tensor = tf.fill(
    dims=[2,3,4],
    value=5,name=None
)

print(fill_tensor)

tf.Tensor(
[[[5 5 5 5]
  [5 5 5 5]
  [5 5 5 5]]

 [[5 5 5 5]
  [5 5 5 5]
  [5 5 5 5]]], shape=(2, 3, 4), dtype=int32)


In [16]:
ones_tensor = tf.ones(
    shape = (2,6,3),
    dtype=tf.dtypes.float32,
    name=None)

print(ones_tensor)

tf.Tensor(
[[[1. 1. 1.]
  [1. 1. 1.]
  [1. 1. 1.]
  [1. 1. 1.]
  [1. 1. 1.]
  [1. 1. 1.]]

 [[1. 1. 1.]
  [1. 1. 1.]
  [1. 1. 1.]
  [1. 1. 1.]
  [1. 1. 1.]
  [1. 1. 1.]]], shape=(2, 6, 3), dtype=float32)


In [17]:
ones_like_tensor = tf.ones_like(
    input=eye_tensor,
    dtype=tf.dtypes.int32,
    name=None
)

print(ones_like_tensor)

tf.Tensor(
[[[1 1 1 1 1]
  [1 1 1 1 1]
  [1 1 1 1 1]
  [1 1 1 1 1]
  [1 1 1 1 1]]

 [[1 1 1 1 1]
  [1 1 1 1 1]
  [1 1 1 1 1]
  [1 1 1 1 1]
  [1 1 1 1 1]]

 [[1 1 1 1 1]
  [1 1 1 1 1]
  [1 1 1 1 1]
  [1 1 1 1 1]
  [1 1 1 1 1]]], shape=(3, 5, 5), dtype=int32)


In [18]:
zeros_tensor = tf.zeros(
    shape = (2,6,3),
    dtype=tf.dtypes.float32,
    name=None)

print(zeros_tensor)

tf.Tensor(
[[[0. 0. 0.]
  [0. 0. 0.]
  [0. 0. 0.]
  [0. 0. 0.]
  [0. 0. 0.]
  [0. 0. 0.]]

 [[0. 0. 0.]
  [0. 0. 0.]
  [0. 0. 0.]
  [0. 0. 0.]
  [0. 0. 0.]
  [0. 0. 0.]]], shape=(2, 6, 3), dtype=float32)


In [19]:
zeros_like_tensor = tf.zeros_like(
    input=eye_tensor,
    dtype=tf.dtypes.int32,
    name=None
)

print(zeros_like_tensor)

tf.Tensor(
[[[0 0 0 0 0]
  [0 0 0 0 0]
  [0 0 0 0 0]
  [0 0 0 0 0]
  [0 0 0 0 0]]

 [[0 0 0 0 0]
  [0 0 0 0 0]
  [0 0 0 0 0]
  [0 0 0 0 0]
  [0 0 0 0 0]]

 [[0 0 0 0 0]
  [0 0 0 0 0]
  [0 0 0 0 0]
  [0 0 0 0 0]
  [0 0 0 0 0]]], shape=(3, 5, 5), dtype=int32)


In [20]:
print(tf.shape(zeros_like_tensor))

tf.Tensor([3 5 5], shape=(3,), dtype=int32)


In [21]:
t = tf.constant([[[1,1,1],[2,2,2]],[[3,3,3],[4,4,4]]])
tf.rank(t)

<tf.Tensor: shape=(), dtype=int32, numpy=3>

In [22]:
t = tf.constant([[1,1,1],[2,2,2]])
tf.rank(t)

<tf.Tensor: shape=(), dtype=int32, numpy=2>

In [23]:
t = tf.constant([[[1,1,1],[2,2,2]],[[3,3,3],[4,4,4]]])
tf.size(t)

<tf.Tensor: shape=(), dtype=int32, numpy=12>

In [25]:
t = tf.constant([[1,1,1],[2,2,2]])
tf.size(t,out_type=tf.float32)

<tf.Tensor: shape=(), dtype=float32, numpy=6.0>

In [34]:
random_normal_tensor = tf.random.normal(
    shape=[3,2],
    mean=0.0,
    stddev=1.0,
    dtype=tf.dtypes.float32,
    seed=None,
    name=None
)

print(random_normal_tensor)

tf.Tensor(
[[ 0.75690836  0.12164332]
 [-1.0512624   1.2117933 ]
 [ 1.621303    0.55317175]], shape=(3, 2), dtype=float32)


In [35]:
random_normal_tensor = tf.random.normal(
    shape=[3,2],
    mean=100.0,
    stddev=10.0,
    dtype=tf.dtypes.float32,
    seed=None,
    name=None
)

print(random_normal_tensor)

tf.Tensor(
[[ 84.28943  101.281296]
 [ 99.55417  106.340355]
 [ 88.26244   89.92159 ]], shape=(3, 2), dtype=float32)


In [36]:
random_uniform_tensor = tf.random.uniform(
    shape=[5,],
    minval=0,
    maxval=None,
    dtype=tf.dtypes.float32,
    seed=None,
    name=None
)

print(random_uniform_tensor)

tf.Tensor([0.6052463  0.38016164 0.17291582 0.32870746 0.8433019 ], shape=(5,), dtype=float32)


In [40]:
random_uniform_tensor = tf.random.uniform(
    shape=[5,5],
    minval=-50,
    maxval=100,
    dtype=tf.dtypes.int32,
    seed=None,
    name=None
)

print(random_uniform_tensor)

tf.Tensor(
[[ 30 -45  15  84 -44]
 [ 73   2 -35  77 -38]
 [  4  16 -41  75  16]
 [ 53 -32  -9 -41  17]
 [-24   2  59  72  60]], shape=(5, 5), dtype=int32)


In [41]:
#function used to set the seed for the random number generators
tf.random.set_seed(5)
print(tf.random.uniform(shape=[3,3],maxval=5,dtype=tf.dtypes.int32,seed=10))
print(tf.random.uniform(shape=[3,3],maxval=5,dtype=tf.dtypes.int32,seed=10))
print(tf.random.uniform(shape=[3,3],maxval=5,dtype=tf.dtypes.int32,seed=10))

tf.Tensor(
[[4 3 1]
 [3 0 1]
 [2 3 1]], shape=(3, 3), dtype=int32)
tf.Tensor(
[[1 3 3]
 [4 4 4]
 [2 4 2]], shape=(3, 3), dtype=int32)
tf.Tensor(
[[4 1 0]
 [2 0 1]
 [0 0 2]], shape=(3, 3), dtype=int32)


In [42]:
tf.random.set_seed(5)
print(tf.random.uniform(shape=[3,3],maxval=5,dtype=tf.dtypes.int32,seed=10))
print(tf.random.uniform(shape=[3,3],maxval=5,dtype=tf.dtypes.int32,seed=10))
print(tf.random.uniform(shape=[3,3],maxval=5,dtype=tf.dtypes.int32,seed=10))

tf.Tensor(
[[4 3 1]
 [3 0 1]
 [2 3 1]], shape=(3, 3), dtype=int32)
tf.Tensor(
[[1 3 3]
 [4 4 4]
 [2 4 2]], shape=(3, 3), dtype=int32)
tf.Tensor(
[[4 1 0]
 [2 0 1]
 [0 0 2]], shape=(3, 3), dtype=int32)


In [43]:
#produces different results
print(tf.random.uniform(shape=[3,3],maxval=5,dtype=tf.dtypes.int32,seed=10))
print(tf.random.uniform(shape=[3,3],maxval=5,dtype=tf.dtypes.int32,seed=10))
print(tf.random.uniform(shape=[3,3],maxval=5,dtype=tf.dtypes.int32,seed=10))

tf.Tensor(
[[4 3 2]
 [0 2 0]
 [0 1 2]], shape=(3, 3), dtype=int32)
tf.Tensor(
[[4 0 4]
 [2 1 0]
 [3 4 0]], shape=(3, 3), dtype=int32)
tf.Tensor(
[[3 0 0]
 [2 0 3]
 [0 2 2]], shape=(3, 3), dtype=int32)
