<a href="https://colab.research.google.com/github/MohneetKaur/Computer-Vision-with-Python-and-Tensorflow/blob/main/Initialization%2CCasting%2CIndexing.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [1]:
import tensorflow as tf

In [2]:
tensor_indexed = tf.constant([3,6,2,4,6,66,7])
print(tensor_indexed)
print('\n')
print(tensor_indexed[0:4])
print('\n')
print(tensor_indexed[1:5+1])
print('\n')
print(tensor_indexed[0:7:2])
print('\n')
print(tensor_indexed[:4])
print('\n')
print(tensor_indexed[4:])
print('\n')
print(tensor_indexed[2:-2])

tf.Tensor([ 3  6  2  4  6 66  7], shape=(7,), dtype=int32)


tf.Tensor([3 6 2 4], shape=(4,), dtype=int32)


tf.Tensor([ 6  2  4  6 66], shape=(5,), dtype=int32)


tf.Tensor([3 2 6 7], shape=(4,), dtype=int32)


tf.Tensor([3 6 2 4], shape=(4,), dtype=int32)


tf.Tensor([ 6 66  7], shape=(3,), dtype=int32)


tf.Tensor([2 4 6], shape=(3,), dtype=int32)


In [3]:
tensor_two_d = tf.constant(
    [[1,2,0],
     [3,5,-1],
     [1,5,6],
     [2,3,8]]
)

print(tensor_two_d[0:2,:])

tf.Tensor(
[[ 1  2  0]
 [ 3  5 -1]], shape=(2, 3), dtype=int32)


In [4]:
tensor_three_d = tf.constant([
    [[1,2,0],
     [3,5,-1],
     [1,5,6],
     [2,3,8]],
    [[2,7,8],
     [0,0,0],
     [3,2,1],
     [4,6,9]]
])

print(tensor_three_d[0,0:2,0:2])
print('\n')
print(tensor_three_d[...,:,2])

tf.Tensor(
[[1 2]
 [3 5]], shape=(2, 2), dtype=int32)


tf.Tensor(
[[ 0 -1  6  8]
 [ 8  0  1  9]], shape=(2, 4), dtype=int32)
