<a href="https://colab.research.google.com/github/MohneetKaur/Computer-Vision-with-Python-and-Tensorflow/blob/main/Common_Tensorflow_Functions.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [2]:
import tensorflow as tf

In [3]:
# Expand dimension function

tensor_three_d = tf.constant([
    [[2,0,1],
     [3,-4,7]],

    [[3,9,10],
     [7,10,4]],

    [[3,0,14],
     [10,1,0]]
])

print(tensor_three_d.shape)
print(tf.expand_dims(tensor_three_d,axis=0).shape, '\n')
print(tf.expand_dims(tensor_three_d,axis=1).shape,'\n')
print(tf.expand_dims(tensor_three_d,axis=2).shape,'\n')
print(tf.expand_dims(tensor_three_d,axis=3).shape)

(3, 2, 3)
(1, 3, 2, 3) 

(3, 1, 2, 3) 

(3, 2, 1, 3) 

(3, 2, 3, 1)


In [33]:
# Expand dimension function

x = tf.constant([2,3,4,5])

print(x.shape, '\n')
print(tf.expand_dims(x, axis=0), '\n')
print(tf.expand_dims(x, axis=1))

(4,) 

tf.Tensor([[2 3 4 5]], shape=(1, 4), dtype=int32) 

tf.Tensor(
[[2]
 [3]
 [4]
 [5]], shape=(4, 1), dtype=int32)


In [34]:
# Expand dimension function

x = tf.constant([[2,3,4,5]])

print(x.shape, '\n')
print(tf.expand_dims(x, axis=1))

(1, 4) 

tf.Tensor([[[2 3 4 5]]], shape=(1, 1, 4), dtype=int32)


In [36]:
# Squeeze method

x = tf.constant([2,3,4,5])

print(x.shape, '\n')

x_expanded = tf.expand_dims(x, axis=0)
print('Expanded Matrix:',x_expanded, '\n')

x_squeezed = tf.squeeze(x_expanded, axis=0)
print('Squeezed Matrix:',x_squeezed, '\n')

(4,) 

Expanded Matrix: tf.Tensor([[2 3 4 5]], shape=(1, 4), dtype=int32) 

Squeezed Matrix: tf.Tensor([2 3 4 5], shape=(4,), dtype=int32) 



In [37]:
# Squeeze Method

x = tf.constant([[[2,3,4,5]]])
print(x.shape, '\n')

x_expanded = tf.expand_dims(x,axis=0)
x_squeezed  = tf.squeeze(x_expanded, axis=0)

for i in range(2):
  x_squeezed = tf.squeeze(x_squeezed, axis=0)

print(x_squeezed)

(1, 1, 4) 

tf.Tensor([2 3 4 5], shape=(4,), dtype=int32)


In [8]:
# Expanding and Squeezing method

tensor_three_d = tf.constant([
    [[2,0,1],
     [3,-4,7]],

    [[3,9,10],
     [7,10,4]],

    [[3,0,14],
     [10,1,0]]
])

print('Original tensor shape:',tensor_three_d.shape)
x_exp = tf.expand_dims(tensor_three_d,axis=3)
print('Shape after expanding:',x_exp.shape, '\n')
print(tf.squeeze(x_exp, axis=3))


Original tensor shape: (3, 2, 3)
Shape after expanding: (3, 2, 3, 1) 

tf.Tensor(
[[[ 2  0  1]
  [ 3 -4  7]]

 [[ 3  9 10]
  [ 7 10  4]]

 [[ 3  0 14]
  [10  1  0]]], shape=(3, 2, 3), dtype=int32)


In [9]:
# Reshape Method

tensor_three_d = tf.constant([
    [[2,0,1],
     [3,-4,7]],

    [[3,9,10],
     [7,10,4]],

    [[3,0,14],
     [10,1,0]]
])

print(tensor_three_d.shape)
x_exp = tf.expand_dims(tensor_three_d,axis=3)

# Reshaping the expanded tensor
print(tf.reshape(x_exp,[3,2,3]).shape)

(3, 2, 3)
(3, 2, 3)


In [10]:
 # Reshape method

x_reshape = tf.constant([[3,5,6,6],
                         [4,6,-1,2]])

print(tf.reshape(x_reshape, [4,-1]), '\n')
print(tf.reshape(x_reshape, [4,2]), '\n')
print(tf.reshape(x_reshape, [8]), '\n')
print(tf.reshape(x_reshape, [-1]), '\n')
print(tf.reshape(x_reshape, [4,2,1]), '\n')

tf.Tensor(
[[ 3  5]
 [ 6  6]
 [ 4  6]
 [-1  2]], shape=(4, 2), dtype=int32) 

tf.Tensor(
[[ 3  5]
 [ 6  6]
 [ 4  6]
 [-1  2]], shape=(4, 2), dtype=int32) 

tf.Tensor([ 3  5  6  6  4  6 -1  2], shape=(8,), dtype=int32) 

tf.Tensor([ 3  5  6  6  4  6 -1  2], shape=(8,), dtype=int32) 

tf.Tensor(
[[[ 3]
  [ 5]]

 [[ 6]
  [ 6]]

 [[ 4]
  [ 6]]

 [[-1]
  [ 2]]], shape=(4, 2, 1), dtype=int32) 



In [11]:
# Concat method

t1 = [[1, 2, 3],
     [4, 5, 6]]

t2 = [[7, 8, 9],
     [10, 11, 12]]

print(tf.constant(t1).shape)
print(tf.constant(t2).shape, '\n')

print(tf.concat([t1, t2], axis=0), '\n')
print(tf.concat([t1, t2], axis=1))

(2, 3)
(2, 3) 

tf.Tensor(
[[ 1  2  3]
 [ 4  5  6]
 [ 7  8  9]
 [10 11 12]], shape=(4, 3), dtype=int32) 

tf.Tensor(
[[ 1  2  3  7  8  9]
 [ 4  5  6 10 11 12]], shape=(2, 6), dtype=int32)


In [12]:
# Concat method

t1 = [[[1, 2, 3],
     [4, 5, 6]]]

t2 = [[[7, 8, 9],
     [10, 11, 12]]]

print(tf.constant(t1).shape)
print(tf.constant(t2).shape, '\n')

print(tf.concat([t1, t2], axis=0), '\n')
print(tf.concat([t1, t2], axis=1), '\n')
print(tf.concat([t1, t2], axis=2), '\n')

# Based on the axis, fix that axis, add its dimension up and the remaining dimensions remain the same

(1, 2, 3)
(1, 2, 3) 

tf.Tensor(
[[[ 1  2  3]
  [ 4  5  6]]

 [[ 7  8  9]
  [10 11 12]]], shape=(2, 2, 3), dtype=int32) 

tf.Tensor(
[[[ 1  2  3]
  [ 4  5  6]
  [ 7  8  9]
  [10 11 12]]], shape=(1, 4, 3), dtype=int32) 

tf.Tensor(
[[[ 1  2  3  7  8  9]
  [ 4  5  6 10 11 12]]], shape=(1, 2, 6), dtype=int32) 



In [13]:
# Stack method along axis=0

print(tf.stack([t1,t2], axis=0), '\n')
print(tf.stack([t1,t2,t1], axis=0), '\n')

"""tf.concat() is used to concatenate tensors along an existing axis without introducing a new axis, requiring the tensors to have the same shape in all
dimensions except the concatenation axis. Conversely, tf.stack() stacks tensors along a new axis, introducing a new axis at the specified position, and
requires the input tensors to have the same shape in all dimensions. While tf.concat() joins tensors end-to-end along the specified axis, tf.stack() stacks
tensors on top of each other along the new axis, resulting in a tensor with a higher rank than the input tensors."""

tf.Tensor(
[[[[ 1  2  3]
   [ 4  5  6]]]


 [[[ 7  8  9]
   [10 11 12]]]], shape=(2, 1, 2, 3), dtype=int32) 

tf.Tensor(
[[[[ 1  2  3]
   [ 4  5  6]]]


 [[[ 7  8  9]
   [10 11 12]]]


 [[[ 1  2  3]
   [ 4  5  6]]]], shape=(3, 1, 2, 3), dtype=int32) 



'tf.concat() is used to concatenate tensors along an existing axis without introducing a new axis, requiring the tensors to have the same shape in all\ndimensions except the concatenation axis. Conversely, tf.stack() stacks tensors along a new axis, introducing a new axis at the specified position, and\nrequires the input tensors to have the same shape in all dimensions. While tf.concat() joins tensors end-to-end along the specified axis, tf.stack() stacks\ntensors on top of each other along the new axis, resulting in a tensor with a higher rank than the input tensors.'

In [14]:
# Stack method along axis=1

print(tf.stack([t1,t2], axis=1), '\n')
print(tf.stack([t1,t2,t1], axis=1), '\n')


tf.Tensor(
[[[[ 1  2  3]
   [ 4  5  6]]

  [[ 7  8  9]
   [10 11 12]]]], shape=(1, 2, 2, 3), dtype=int32) 

tf.Tensor(
[[[[ 1  2  3]
   [ 4  5  6]]

  [[ 7  8  9]
   [10 11 12]]

  [[ 1  2  3]
   [ 4  5  6]]]], shape=(1, 3, 2, 3), dtype=int32) 



In [15]:
# Stack method along axis=2

print(tf.stack([t1,t2], axis=2), '\n')
print(tf.stack([t1,t2,t1], axis=2), '\n')

tf.Tensor(
[[[[ 1  2  3]
   [ 7  8  9]]

  [[ 4  5  6]
   [10 11 12]]]], shape=(1, 2, 2, 3), dtype=int32) 

tf.Tensor(
[[[[ 1  2  3]
   [ 7  8  9]
   [ 1  2  3]]

  [[ 4  5  6]
   [10 11 12]
   [ 4  5  6]]]], shape=(1, 2, 3, 3), dtype=int32) 



In [16]:
"""
4,3 - 4,3 --> 2,4,3 (axis=0)
4,3 - 4,3 --> 4,2,3 (axis=1)
4,3 - 4,3 --> 4,3,2 (axis=2)
"""

'\n4,3 - 4,3 --> 2,4,3 (axis=0)\n4,3 - 4,3 --> 4,2,3 (axis=1)\n4,3 - 4,3 --> 4,3,2 (axis=2)\n'

In [17]:
# Stack method

t1 = [[1,2,3],
      [4,5,6],
      [7,8,9],
      [10,11,12]]

t2 = [[1,2,3],
      [4,5,6],
      [7,8,9],
      [10,11,12]]

print(tf.stack([t1,t2], axis=0),'\n')
print(tf.stack([t1,t2], axis=1),'\n')

tf.Tensor(
[[[ 1  2  3]
  [ 4  5  6]
  [ 7  8  9]
  [10 11 12]]

 [[ 1  2  3]
  [ 4  5  6]
  [ 7  8  9]
  [10 11 12]]], shape=(2, 4, 3), dtype=int32) 

tf.Tensor(
[[[ 1  2  3]
  [ 1  2  3]]

 [[ 4  5  6]
  [ 4  5  6]]

 [[ 7  8  9]
  [ 7  8  9]]

 [[10 11 12]
  [10 11 12]]], shape=(4, 2, 3), dtype=int32) 



In [18]:
print(tf.stack([t1,t2,t1], axis=0),'\n')
print(tf.stack([t1,t2,t1], axis=1),'\n')

tf.Tensor(
[[[ 1  2  3]
  [ 4  5  6]
  [ 7  8  9]
  [10 11 12]]

 [[ 1  2  3]
  [ 4  5  6]
  [ 7  8  9]
  [10 11 12]]

 [[ 1  2  3]
  [ 4  5  6]
  [ 7  8  9]
  [10 11 12]]], shape=(3, 4, 3), dtype=int32) 

tf.Tensor(
[[[ 1  2  3]
  [ 1  2  3]
  [ 1  2  3]]

 [[ 4  5  6]
  [ 4  5  6]
  [ 4  5  6]]

 [[ 7  8  9]
  [ 7  8  9]
  [ 7  8  9]]

 [[10 11 12]
  [10 11 12]
  [10 11 12]]], shape=(4, 3, 3), dtype=int32) 



In [19]:
print(tf.stack([t1,t2,t1], axis=2),'\n')
print(tf.stack([t1,t2,t1], axis=2),'\n')

tf.Tensor(
[[[ 1  1  1]
  [ 2  2  2]
  [ 3  3  3]]

 [[ 4  4  4]
  [ 5  5  5]
  [ 6  6  6]]

 [[ 7  7  7]
  [ 8  8  8]
  [ 9  9  9]]

 [[10 10 10]
  [11 11 11]
  [12 12 12]]], shape=(4, 3, 3), dtype=int32) 

tf.Tensor(
[[[ 1  1  1]
  [ 2  2  2]
  [ 3  3  3]]

 [[ 4  4  4]
  [ 5  5  5]
  [ 6  6  6]]

 [[ 7  7  7]
  [ 8  8  8]
  [ 9  9  9]]

 [[10 10 10]
  [11 11 11]
  [12 12 12]]], shape=(4, 3, 3), dtype=int32) 



In [20]:
# Same can be performed using expand_dims method

print(tf.stack([t1,t2],axis=0), '\n')

print(tf.concat([tf.expand_dims(t,axis=0) for t in [t1,t2]],axis=0))

tf.Tensor(
[[[ 1  2  3]
  [ 4  5  6]
  [ 7  8  9]
  [10 11 12]]

 [[ 1  2  3]
  [ 4  5  6]
  [ 7  8  9]
  [10 11 12]]], shape=(2, 4, 3), dtype=int32) 

tf.Tensor(
[[[ 1  2  3]
  [ 4  5  6]
  [ 7  8  9]
  [10 11 12]]

 [[ 1  2  3]
  [ 4  5  6]
  [ 7  8  9]
  [10 11 12]]], shape=(2, 4, 3), dtype=int32)


In [21]:
# Padding method

t = tf.constant([[1, 2, 3], [4, 5, 6]])

paddings = tf.constant([
    [1, 1,], # One row above, one row below
     [2, 4] # Two columns left, four columns right
    ])

# 'constant_values' is 0.
# rank of 't' is 2.

print(tf.pad(t, paddings, "CONSTANT"), '\n')

print(tf.pad(t, paddings, "CONSTANT", constant_values=3))

tf.Tensor(
[[0 0 0 0 0 0 0 0 0]
 [0 0 1 2 3 0 0 0 0]
 [0 0 4 5 6 0 0 0 0]
 [0 0 0 0 0 0 0 0 0]], shape=(4, 9), dtype=int32) 

tf.Tensor(
[[3 3 3 3 3 3 3 3 3]
 [3 3 1 2 3 3 3 3 3]
 [3 3 4 5 6 3 3 3 3]
 [3 3 3 3 3 3 3 3 3]], shape=(4, 9), dtype=int32)


In [22]:
t = tf.constant([[1, 2, 3], [4, 5, 6]])

paddings = tf.constant([
    [1, 1,], # One row above, one row below
     [2, 2] # Two columns left, two columns right
    ])

tf.pad(t, paddings, "REFLECT")

<tf.Tensor: shape=(4, 7), dtype=int32, numpy=
array([[6, 5, 4, 5, 6, 5, 4],
       [3, 2, 1, 2, 3, 2, 1],
       [6, 5, 4, 5, 6, 5, 4],
       [3, 2, 1, 2, 3, 2, 1]], dtype=int32)>

In [23]:
tf.pad(t, paddings, "SYMMETRIC")

<tf.Tensor: shape=(4, 7), dtype=int32, numpy=
array([[2, 1, 1, 2, 3, 3, 2],
       [2, 1, 1, 2, 3, 3, 2],
       [5, 4, 4, 5, 6, 6, 5],
       [5, 4, 4, 5, 6, 6, 5]], dtype=int32)>

In [24]:
# Gather method

params = tf.constant(['p0', 'p1', 'p2', 'p3', 'p4', 'p5'])

print(params[1:4].numpy(),'\n')

print(tf.gather(params, tf.range(1,4)).numpy(),'\n')

print(tf.gather(params, [0,5,3]).numpy())

[b'p1' b'p2' b'p3'] 

[b'p1' b'p2' b'p3'] 

[b'p0' b'p5' b'p3']


In [25]:
params = tf.constant([[0, 1.0, 2.0],
                      [10.0, 11.0, 12.0],
                      [20.0, 21.0, 22.0],
                      [30.0, 31.0, 32.0]])

print(tf.gather(params, indices=[3,1]).numpy(),'\n') # fetched 3rd row and 1st row and default axis=0

print(tf.gather(params, indices=[2,1], axis=1).numpy(),'\n')

[[30. 31. 32.]
 [10. 11. 12.]] 

[[ 2.  1.]
 [12. 11.]
 [22. 21.]
 [32. 31.]] 



In [26]:
params = tf.constant([
    [[0, 1.0, 2.0],
    [10.0, 11.0, 12.0],
    [20.0, 21.0, 22.0],
    [30.0, 31.0, 32.0]]
  ])

print(params.shape,'\n')

print(tf.gather(params, indices=[2,1], axis=1))

(1, 4, 3) 

tf.Tensor(
[[[20. 21. 22.]
  [10. 11. 12.]]], shape=(1, 2, 3), dtype=float32)


In [27]:
params = tf.constant([
    [[0, 1.0, 2.0],
    [10.0, 11.0, 12.0],
    [20.0, 21.0, 22.0],
    [30.0, 31.0, 32.0]],

   [[0, 1.0, 2.0],
    [10.0, 11.0, 12.0],
    [20.0, 21.0, 22.0],
    [30.0, 31.0, 32.0]]

  ])


print(params.shape,'\n')

print(tf.gather(params, indices=[1,2], axis=2))

(2, 4, 3) 

tf.Tensor(
[[[ 1.  2.]
  [11. 12.]
  [21. 22.]
  [31. 32.]]

 [[ 1.  2.]
  [11. 12.]
  [21. 22.]
  [31. 32.]]], shape=(2, 4, 2), dtype=float32)


In [28]:
# gather_nd method

indices = [[1],
           [2]]

params = [['a','b'],
          ['c','d'],
          ['e','f']]

tf.gather_nd(params, indices)

<tf.Tensor: shape=(2, 2), dtype=string, numpy=
array([[b'c', b'd'],
       [b'e', b'f']], dtype=object)>

In [29]:
indices = [[0,1],[1,0]]

params = [[['a0','b0'],
           ['c0','d0']],

          [['a1','b1'],
           ['c1','d1']]]

tf.gather_nd(params, indices)

<tf.Tensor: shape=(2, 2), dtype=string, numpy=
array([[b'c0', b'd0'],
       [b'a1', b'b1']], dtype=object)>

In [30]:
indices = [[[0,1],
            [1,0]],

           [[0,0],
            [1,1]]]

params = [[['a0','b0'],
           ['c0','d0']],

          [['a1','b1'],
           ['c1','d1']]]

tf.gather_nd(params, indices)

<tf.Tensor: shape=(2, 2, 2), dtype=string, numpy=
array([[[b'c0', b'd0'],
        [b'a1', b'b1']],

       [[b'a0', b'b0'],
        [b'c1', b'd1']]], dtype=object)>

In [31]:
indices = [[[0,1],
            [1,0]],

           [[0,0],
            [1,1]]]

params = [[['a0','b0'],
           ['c0','d0']],

          [['a1','b1'],
           ['c1','d1']]]

tf.gather_nd(params, indices, batch_dims=1)

<tf.Tensor: shape=(2, 2), dtype=string, numpy=
array([[b'b0', b'c0'],
       [b'a1', b'd1']], dtype=object)>