<a href="https://colab.research.google.com/github/MohneetKaur/Computer-Vision-with-Python-and-Tensorflow/blob/main/9.%20Variables.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [13]:
import tensorflow as tf

In [14]:
x = tf.constant([1,2])

x_var = tf.Variable(x, name='var1')
print(x_var)

<tf.Variable 'var1:0' shape=(2,) dtype=int32, numpy=array([1, 2], dtype=int32)>


In [15]:
# assign method

x_var.assign([2,3])

<tf.Variable 'UnreadVariable' shape=(2,) dtype=int32, numpy=array([2, 3], dtype=int32)>

In [16]:
# Convert variable value to a NumPy array
value_np = x_var.numpy()
value_np

array([2, 3], dtype=int32)

In [17]:
# assign_add method

x_var.assign_add([2,2])

<tf.Variable 'UnreadVariable' shape=(2,) dtype=int32, numpy=array([4, 5], dtype=int32)>

In [18]:
# assign_sub method

x_var.assign_sub([4,5])

<tf.Variable 'UnreadVariable' shape=(2,) dtype=int32, numpy=array([0, 0], dtype=int32)>

In [19]:
with tf.device('CPU:0'):
  x_1 = tf.constant([1,2,3])
  x_2 = tf.constant([1])

with tf.device('GPU:0'): #  it moves the computation to the GPU for better performance since x_1 and x_2 are on different devices.
  x_3 = x_1 + x_2

print(x_1,x_1.device)
print(x_2,x_2.device)
print(x_3,x_3.device)

tf.Tensor([1 2 3], shape=(3,), dtype=int32) /job:localhost/replica:0/task:0/device:CPU:0
tf.Tensor([1], shape=(1,), dtype=int32) /job:localhost/replica:0/task:0/device:CPU:0
tf.Tensor([2 3 4], shape=(3,), dtype=int32) /job:localhost/replica:0/task:0/device:GPU:0


In [20]:
# read_value method

# Read the current value of the variable
current_value = x_var.read_value()
print(current_value)


tf.Tensor([0 0], shape=(2,), dtype=int32)


In [21]:
# Get the name of the variable
print(x_var.name)

# Check if the variable is trainable
print(x_var.trainable)


var1:0
True


In [22]:
# Get the shape of the variable
print(x_var.shape)

(2,)


In [23]:
# Save the variable's value to a checkpoint
tf.train.Checkpoint(var=x_var).save('checkpoint')

'checkpoint-1'

In [24]:
# Restore the variable's value from a checkpoint
tf.train.Checkpoint(var=x_var).restore('checkpoint-1')
