<a href="https://colab.research.google.com/github/MohneetKaur/Computer-Vision-with-Python-and-Tensorflow/blob/main/Linear_Algebra_Operations.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [32]:
import tensorflow as tf

In [33]:
#Matrix Multiplication

x_1 = tf.constant([[1,2,0]])
x_2 = tf.constant([[1,2,0,2],
                   [3,5,-1,2],
                   [4,5,6,0]])

print(x_1.shape,x_2.shape)
tf.linalg.matmul(x_1,x_2,transpose_a=False,transpose_b=False,adjoint_a=False,
                 adjoint_b=False,a_is_sparse=False,b_is_sparse=False,output_type=None,
                 name=None
                 )

(1, 3) (3, 4)


<tf.Tensor: shape=(1, 4), dtype=int32, numpy=array([[ 7, 12, -2,  6]], dtype=int32)>

In [34]:
# ALternate method for matrix multiplication
x_1@x_2

<tf.Tensor: shape=(1, 4), dtype=int32, numpy=array([[ 7, 12, -2,  6]], dtype=int32)>

In [35]:
x_2 = tf.constant([[1,2,0,2],
                   [3,5,-1,2],
                   [4,5,6,0]])
x_1 = tf.constant([[1,2,0]])


print(x_1.shape,x_2.shape)
tf.linalg.matmul(x_2,x_1,transpose_a=True,transpose_b=True,adjoint_a=False,
                 adjoint_b=False,a_is_sparse=False,b_is_sparse=False,output_type=None,
                 name=None
                 )

(1, 3) (3, 4)


<tf.Tensor: shape=(4, 1), dtype=int32, numpy=
array([[ 7],
       [12],
       [-2],
       [ 6]], dtype=int32)>

In [36]:
x_2 = tf.constant([[1,2,0,2],
                   [3,5,-1,2],
                   [4,5,6,0]])
x_1 = tf.constant([[1,2,0]])

print(tf.transpose(x_2)@tf.transpose(x_1))

tf.Tensor(
[[ 7]
 [12]
 [-2]
 [ 6]], shape=(4, 1), dtype=int32)


In [37]:
# Transpose of a matrix

x_1 = tf.constant([[1,2,0,2],
                   [3,5,-1,2],
                   [4,5,6,0]])

x_1_transpose = tf.transpose(x_1)

print('x_1 shape:',x_1.shape)
print('x_1_transpose shape:',x_1_transpose.shape)

x_1 shape: (3, 4)
x_1_transpose shape: (4, 3)


In [38]:
# Matrix Multiplication in batches

x_1 = tf.constant([[[1,2],
                    [3,5]],

                   [[10,2],
                    [1,0]],

                   [[5,8],
                    [2,7]]])

# (2,2)*(2,3) --> (2,3)

x_2 = tf.constant([[[5,1,4],
                    [34,15,1]],

                   [[1,2,2],
                    [5,3,2]],

                   [[2,2,3],
                    [1,1,1]]])

print('Matrix Multiplication: \n',tf.linalg.matmul(x_1,x_2))

Matrix Multiplication: 
 tf.Tensor(
[[[ 73  31   6]
  [185  78  17]]

 [[ 20  26  24]
  [  1   2   2]]

 [[ 18  18  23]
  [ 11  11  13]]], shape=(3, 2, 3), dtype=int32)


In [39]:
# Adjoint of a matrix

x = tf.constant([[1,2,0],
                   [3,5,-1],
                   [4,5,6]])

tf.linalg.adjoint(x)

<tf.Tensor: shape=(3, 3), dtype=int32, numpy=
array([[ 1,  3,  4],
       [ 2,  5,  5],
       [ 0, -1,  6]], dtype=int32)>

In [40]:
# band_part

tensor_two_d = tf.constant([[1,-2,0],
                            [3,5,100],
                            [1,5,6],
                            [2,3,8]],dtype=tf.float16)

### in_band(m, n) = (num_lower < 0 || (m-n) <= num_lower)) && (num_upper < 0 || (n-m) <= num_upper)

# m--rows, n--columns

tf.linalg.band_part(input=tensor_two_d,num_lower=0,num_upper=0)

<tf.Tensor: shape=(4, 3), dtype=float16, numpy=
array([[1., 0., 0.],
       [0., 5., 0.],
       [0., 0., 6.],
       [0., 0., 0.]], dtype=float16)>

In [41]:
"""
tensor_two_d_m_n = tf.constant([[0,-1,-2],
                                [1,0,-1],
                                [2,1,0],
                                [3,2,1]],dtype=tf.float16)

tensor_two_d_n_m = tf.constant([[0,1,2],
                                [-1,0,1],
                                [-2,-1,0],
                                [-3,-2,-2]],dtype=tf.float16)

"""

' \ntensor_two_d_m_n = tf.constant([[0,-1,-2],\n                                [1,0,-1],\n                                [2,1,0],\n                                [3,2,1]],dtype=tf.float16) \n\ntensor_two_d_n_m = tf.constant([[0,1,2],\n                                [-1,0,1],\n                                [-2,-1,0],\n                                [-3,-2,-2]],dtype=tf.float16)\n\n'

In [42]:
# Use Cases of band_part --> Upper triangular matrix

tf.linalg.band_part(input=tensor_two_d, num_lower=0,num_upper=-1)

<tf.Tensor: shape=(4, 3), dtype=float16, numpy=
array([[  1.,  -2.,   0.],
       [  0.,   5., 100.],
       [  0.,   0.,   6.],
       [  0.,   0.,   0.]], dtype=float16)>

In [43]:
# Use Cases of band_part --> Lower triangular matrix

tf.linalg.band_part(input=tensor_two_d, num_lower=-1, num_upper=0)

<tf.Tensor: shape=(4, 3), dtype=float16, numpy=
array([[1., 0., 0.],
       [3., 5., 0.],
       [1., 5., 6.],
       [2., 3., 8.]], dtype=float16)>

In [44]:
# Use Cases of band_part --> Diagonal

tf.linalg.band_part(input=tensor_two_d, num_lower=0, num_upper=0)

<tf.Tensor: shape=(4, 3), dtype=float16, numpy=
array([[1., 0., 0.],
       [0., 5., 0.],
       [0., 0., 6.],
       [0., 0., 0.]], dtype=float16)>

In [45]:
# Determinant of a matrix

x = tf.constant([[1,2,0],
                 [2,3,4],
                 [1,0,0]], dtype=tf.float32)

print('Determinant:',tf.linalg.det(input=x, name=None))

Determinant: tf.Tensor(8.0, shape=(), dtype=float32)


In [46]:
# Inverse of a matrix - should be a square matrix

x = tf.constant([[1,2,0],
                 [2,3,4],
                 [1,0,0]], dtype=tf.float32)

x_inv = tf.linalg.inv(input=x, name=None)

print(x_inv)

tf.Tensor(
[[ 0.     0.     1.   ]
 [ 0.5   -0.    -0.5  ]
 [-0.375  0.25  -0.125]], shape=(3, 3), dtype=float32)


In [47]:
# Matrix Multiplication of a matrix with its inverse

x@x_inv

<tf.Tensor: shape=(3, 3), dtype=float32, numpy=
array([[1., 0., 0.],
       [0., 1., 0.],
       [0., 0., 1.]], dtype=float32)>

In [48]:
# Singular Value Decomposition of a matrix

tensor_two_d = tf.constant([[1,-2,0],
                            [3,5,100],
                            [1,5,6],
                            [2,3,8]],dtype=tf.float32)

s, u, v = tf.linalg.svd(tensor_two_d)

# s is a tensor of singular values.
# u is a tensor of left singular vectors.
# v is a tensor of right singular vectors.

print(s)
print(u)
print(v)

tf.Tensor([100.70144     5.8190866   1.8329673], shape=(3,), dtype=float32)
tf.Tensor(
[[-7.74652755e-04 -2.99280852e-01  7.63974667e-01]
 [ 9.94706869e-01 -9.16284993e-02 -4.46390249e-02]
 [ 6.25059605e-02  8.12258899e-01 -1.08075924e-01]
 [ 8.15519020e-02  4.92210150e-01  6.34563029e-01]], shape=(4, 3), dtype=float32)
tf.Tensor(
[[ 0.03186604  0.21008667  0.9771634 ]
 [ 0.05493734  0.97581375 -0.21158805]
 [ 0.99798125 -0.06042523 -0.01955372]], shape=(3, 3), dtype=float32)


In [49]:
 # Einsum Operation

import numpy as np

A = np.array([[2,6,5,2],
               [2,-2,2,3],
               [1,5,4,0]])

B = np.array([[2,9,0,3,0],
               [3,6,8,-2,2],
               [1,3,5,0,1],
               [3,0,2,0,5]])

print(A.shape)
print(B.shape)

print('Matmul operation: \n')
print(np.matmul(A,B),'\n')

print('Einsum operation: \n')
# The 'ij,jk->ik' string specifies the Einstein summation convention for matrix multiplication.
print(np.einsum('ij,jk->ik', A, B))

(3, 4)
(4, 5)
Matmul operation: 

[[33 69 77 -6 27]
 [ 9 12  0 10 13]
 [21 51 60 -7 14]] 

Einsum operation: 

[[33 69 77 -6 27]
 [ 9 12  0 10 13]
 [21 51 60 -7 14]]


In [50]:
# Element wise multiplication

A = np.array([[2,6,5,2],
               [2,-2,2,3],
               [1,5,4,0]])

B = np.array([[2,9,0,3],
               [3,6,8,-2],
               [1,3,5,0]])

print(A.shape) # (3,3)
print(B.shape) # (3,3)

print('Element wise multiplication using * : \n')
print(A*B,'\n')

print('Einsum operation: \n')
# The 'ij,jk->ik' string specifies the Einstein summation convention for matrix multiplication.
print(np.einsum('ij,ij->ij', A, B))

(3, 4)
(3, 4)
Element wise multiplication using * : 

[[  4  54   0   6]
 [  6 -12  16  -6]
 [  1  15  20   0]] 

Einsum operation: 

[[  4  54   0   6]
 [  6 -12  16  -6]
 [  1  15  20   0]]


In [51]:
# Transpose of a matrix by einsum method

A = np.array([[2,6,5,2],
              [2,-2,2,3],
              [1,5,4,0]])

print("Transposed A: \n")
print(A.T,"\n")

print("Einsum Transpose A:\n")
print(np.einsum("ij -> ji",A))

Transposed A: 

[[ 2  2  1]
 [ 6 -2  5]
 [ 5  2  4]
 [ 2  3  0]] 

Einsum Transpose A:

[[ 2  2  1]
 [ 6 -2  5]
 [ 5  2  4]
 [ 2  3  0]]


In [52]:
# Matrix Multiplication by einsum method

A = np.array([[[2,6,5,2],
               [2,-2,2,3],
               [1,5,4,0]],

              [[1,3,1,22],
               [0,2,2,0],
               [1,5,4,1]]])

B = np.array([[[2,9,0,3,0],
               [3,6,8,-2,2],
               [1,3,5,0,1],
               [3,0,2,0,5]],

              [[1,0,0,3,0],
               [3,0,4,-2,2],
               [1,0,2,0,0],
               [3,0,1,1,0]]])

print(A.shape,B.shape)

print("Batch Multiplication:\n")
print(np.matmul(A,B),'\n')

print('Einsum Method:\n')
print(np.einsum("bij,bjk -> bik",A,B))

(2, 3, 4) (2, 4, 5)
Batch Multiplication:

[[[33 69 77 -6 27]
  [ 9 12  0 10 13]
  [21 51 60 -7 14]]

 [[77  0 36 19  6]
  [ 8  0 12 -4  4]
  [23  0 29 -6 10]]] 

Einsum Method:

[[[33 69 77 -6 27]
  [ 9 12  0 10 13]
  [21 51 60 -7 14]]

 [[77  0 36 19  6]
  [ 8  0 12 -4  4]
  [23  0 29 -6 10]]]


In [53]:
# Sum using einsum method

A = np.array([[[2,6,5,2],
               [2,-2,2,3],
               [1,5,4,0]],

              [[1,3,1,22],
               [0,2,2,0],
               [1,5,4,1]]])

print("SUm of A:\n")
print(np.sum(A),'\n')

print("Einsum A:\n")
print(np.einsum('bij -> ',A))

SUm of A:

72 

Einsum A:

72


In [54]:
# Column wise sum using einsum method

A = np.array([[2,6,5,2],
               [2,-2,2,3],
               [1,5,4,0]])

print("Axis 0 SUm A: \n")
print(np.sum(A,axis=0),"\n")

print("Einsum A: \n")
print(np.einsum('ij -> j', A))

Axis 0 SUm A: 

[ 5  9 11  5] 

Einsum A: 

[ 5  9 11  5]


In [55]:
# Row wise sum using einsum method

A = np.array([[2,6,5,2],
               [2,-2,2,3],
               [1,5,4,0]])

print("Axis 1 SUm A: \n")
print(np.sum(A,axis=1),"\n")

print("Einsum A: \n")
print(np.einsum('ij -> i', A))

Axis 1 SUm A: 

[15  5 10] 

Einsum A: 

[15  5 10]


In [56]:
# Example from 'Attention Is All You Need' paper

Q = np.random.randn(32,64,512)
K = np.random.randn(32,128,512)

In [57]:
np.einsum('bqm,bkm',Q,K)

array([[  93.85495483,  -11.08782093,  -55.44458376, ...,  -10.50138631,
          22.96346083,  -66.97203602],
       [  84.40340345,  -72.82551586, -115.74071704, ...,   80.61515776,
           9.34230827, -224.97100687],
       [ 201.02783336,  -78.49695474, -109.65717223, ...,  -65.96107503,
          98.55907111,    0.85703016],
       ...,
       [ 114.8773318 ,  -51.99053971, -149.65599493, ...,    2.61716584,
         -61.85654683,   88.5832663 ],
       [ 148.25077012,  -13.95029001,  110.65454683, ...,   -8.7338804 ,
         -90.94579291, -242.31441658],
       [ 224.55554949, -247.75798758,  -53.68941817, ...,   83.31668779,
        -136.35688345,   27.34163305]])

In [58]:
np.einsum('bqm,bkm',Q,K).shape

(128, 64)

In [59]:
# Example-2

A = np.random.randn(2,4,4,2) # bcij
B = np.random.randn(2,4,4,1) # bcik

In [60]:
np.einsum("bcik,bcij -> bckj", B, A)

array([[[[ 0.12788976, -1.49358148]],

        [[-0.22120038, -0.06785165]],

        [[-2.35789451,  2.42209577]],

        [[-1.63657152, -0.88264405]]],


       [[[ 0.84815775, -1.37684437]],

        [[-4.14278475, -1.26561325]],

        [[ 0.45416327,  0.33195679]],

        [[ 0.81217276,  0.44511186]]]])

In [61]:
np.einsum("bcik,bcij -> bckj", A, B)

array([[[[ 0.12788976],
         [-1.49358148]],

        [[-0.22120038],
         [-0.06785165]],

        [[-2.35789451],
         [ 2.42209577]],

        [[-1.63657152],
         [-0.88264405]]],


       [[[ 0.84815775],
         [-1.37684437]],

        [[-4.14278475],
         [-1.26561325]],

        [[ 0.45416327],
         [ 0.33195679]],

        [[ 0.81217276],
         [ 0.44511186]]]])