<a href="https://colab.research.google.com/github/MohneetKaur/Computer-Vision-with-Python-and-Tensorflow/blob/main/Math_Operations.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [1]:
import tensorflow as tf

In [2]:
x_abs = tf.constant([-2.25,3.25])
tf.abs(x_abs)

<tf.Tensor: shape=(2,), dtype=float32, numpy=array([2.25, 3.25], dtype=float32)>

In [3]:
x_abs_complex = tf.constant([-2.25+4.75j])
tf.abs(x_abs_complex)

<tf.Tensor: shape=(1,), dtype=float64, numpy=array([5.25594901])>

In [4]:
tf.sqrt((-2.25)**2+4.75**2)

<tf.Tensor: shape=(), dtype=float32, numpy=5.255949>

In [5]:
x_1 = tf.constant([5,3,6,6,7,4],dtype=tf.int32)
x_2 = tf.constant([2,4,6,9,10,1],dtype=tf.int32)
print(tf.add(x_1,x_2))

tf.Tensor([ 7  7 12 15 17  5], shape=(6,), dtype=int32)


In [6]:
x_1 = tf.constant([[5,3,6,6,7,4],[5,45,65,5,53,4]],dtype=tf.float32)
x_2 = tf.constant([7],dtype=tf.float32)
x_2_stretched = tf.constant([7,7,7,7,7,7],dtype=tf.float32)

print(tf.math.add(x_1,x_2))
print(tf.math.add(x_1,x_2_stretched))

tf.Tensor(
[[12. 10. 13. 13. 14. 11.]
 [12. 52. 72. 12. 60. 11.]], shape=(2, 6), dtype=float32)
tf.Tensor(
[[12. 10. 13. 13. 14. 11.]
 [12. 52. 72. 12. 60. 11.]], shape=(2, 6), dtype=float32)


In [7]:
x_1 = tf.constant([5,3,6,6,7,4],dtype=tf.int32)
x_2 = tf.constant([2,4,6,9,10,1],dtype=tf.int32)
print(tf.multiply(x_1,x_2))

tf.Tensor([10 12 36 54 70  4], shape=(6,), dtype=int32)


In [8]:
x_1 = tf.constant([[5,3,6,6,7,4],[5,45,65,5,53,4]],dtype=tf.float32)
x_2 = tf.constant([7],dtype=tf.float32)
x_2_stretched = tf.constant([7,7,7,7,7,7],dtype=tf.float32)

print(tf.math.multiply(x_1,x_2))
print(tf.math.multiply(x_1,x_2_stretched))

tf.Tensor(
[[ 35.  21.  42.  42.  49.  28.]
 [ 35. 315. 455.  35. 371.  28.]], shape=(2, 6), dtype=float32)
tf.Tensor(
[[ 35.  21.  42.  42.  49.  28.]
 [ 35. 315. 455.  35. 371.  28.]], shape=(2, 6), dtype=float32)


In [9]:
x_1 = tf.constant([[5,3,6,6,7,4],],dtype=tf.float32)
x_2 = tf.constant([[7],[5],[3]],dtype=tf.float32)


print(x_1.shape)
print(x_2.shape)
print(tf.math.multiply(x_1,x_2))

(1, 6)
(3, 1)
tf.Tensor(
[[35. 21. 42. 42. 49. 28.]
 [25. 15. 30. 30. 35. 20.]
 [15.  9. 18. 18. 21. 12.]], shape=(3, 6), dtype=float32)


In [10]:
x_1 = tf.constant([5,3,6,6,7,4],dtype=tf.int32)
x_2 = tf.constant([2,4,6,9,10,1],dtype=tf.int32)
print(tf.subtract(x_1,x_2))

tf.Tensor([ 3 -1  0 -3 -3  3], shape=(6,), dtype=int32)


In [11]:
x_1 = tf.constant([5,3,6,6,7,4],dtype=tf.float32)
x_2 = tf.constant([2,4,6,9,10,0],dtype=tf.float32)
print(tf.divide(x_1,x_2))

tf.Tensor([2.5       0.75      1.        0.6666667 0.7             inf], shape=(6,), dtype=float32)


In [12]:
x_1 = tf.constant([5,3,6,6,7,4],dtype=tf.float32)
x_2 = tf.constant([2,4,6,9,10,0],dtype=tf.float32)
print(tf.math.divide_no_nan(x_1,x_2))

tf.Tensor([2.5       0.75      1.        0.6666667 0.7       0.       ], shape=(6,), dtype=float32)


In [13]:
x_argmax = tf.constant([2,20,30,3,6])

print(x_argmax.shape)
print(tf.math.argmax(x_argmax))

(5,)
tf.Tensor(2, shape=(), dtype=int64)


In [14]:
x_argmax = tf.constant([[2,20,30,3,6],
                        [3,11,16,1,80],
                        [14,45,23,5,27]])

print(x_argmax.shape)
print(tf.math.argmax(x_argmax))
print(tf.math.argmax(x_argmax,0))
print(tf.math.argmax(x_argmax,1))

(3, 5)
tf.Tensor([2 2 0 2 1], shape=(5,), dtype=int64)
tf.Tensor([2 2 0 2 1], shape=(5,), dtype=int64)
tf.Tensor([2 4 1], shape=(3,), dtype=int64)


In [15]:
x_argmin = tf.constant([[2,20,30,3,6],
                        [3,11,16,1,80],
                        [14,45,23,5,27]])

print(x_argmin.shape)
print(tf.math.argmin(x_argmin))
print(tf.math.argmin(x_argmin,0))
print(tf.math.argmin(x_argmin,1))

(3, 5)
tf.Tensor([0 1 1 1 0], shape=(5,), dtype=int64)
tf.Tensor([0 1 1 1 0], shape=(5,), dtype=int64)
tf.Tensor([0 3 3], shape=(3,), dtype=int64)


In [16]:
x=tf.constant([2,4])
y=tf.constant([2])
print(tf.math.equal(x,y))

tf.Tensor([ True False], shape=(2,), dtype=bool)


In [17]:
x=tf.constant([2,4])
y=tf.constant([7,4])
print(tf.math.equal(x,y))

tf.Tensor([False  True], shape=(2,), dtype=bool)


In [18]:
x=tf.constant([[2,3],[4,5]])
y=tf.constant([[3,3],[2,2]])
tf.pow(x,y)

<tf.Tensor: shape=(2, 2), dtype=int32, numpy=
array([[ 8, 27],
       [16, 25]], dtype=int32)>

In [19]:
tensor_two_d = tf.constant([[1,2,0],
                            [3,5,-1],
                            [1,5,6],
                            [2,3,8]],dtype=tf.float16)

print(tf.math.reduce_sum(tensor_two_d,axis=None,keepdims=False,name=None))
print(tf.math.reduce_sum(tensor_two_d,axis=1,keepdims=False,name=None))
print(tf.math.reduce_sum(tensor_two_d,axis=0,keepdims=False,name=None))
print('\n')
print(tf.math.reduce_max(tensor_two_d,axis=None,keepdims=False,name=None))
print('\n')
print(tf.math.reduce_min(tensor_two_d,axis=None,keepdims=False,name=None))
print('\n')
print(tf.math.reduce_mean(tensor_two_d,axis=None,keepdims=False,name=None))
print('\n')
print(tf.math.reduce_std(tensor_two_d,axis=None,keepdims=False,name=None))
print(tf.math.reduce_std(tensor_two_d,axis=None,keepdims=True,name=None))


tf.Tensor(35.0, shape=(), dtype=float16)
tf.Tensor([ 3.  7. 12. 13.], shape=(4,), dtype=float16)
tf.Tensor([ 7. 15. 13.], shape=(3,), dtype=float16)


tf.Tensor(8.0, shape=(), dtype=float16)


tf.Tensor(-1.0, shape=(), dtype=float16)


tf.Tensor(2.916, shape=(), dtype=float16)


tf.Tensor(2.531, shape=(), dtype=float16)
tf.Tensor([[2.531]], shape=(1, 1), dtype=float16)


In [21]:
x = tf.constant([0,1,50,100],dtype=tf.float16)
tf.math.sigmoid(x)

<tf.Tensor: shape=(4,), dtype=float16, numpy=array([0.5  , 0.731, 1.   , 1.   ], dtype=float16)>

In [26]:
tensor_two_d = tf.constant([[1,2,0],
                            [3,5,-1],
                            [1,5,6],
                            [2,3,8]],dtype=tf.float16)

tf.math.top_k(tensor_two_d,k=1,sorted=True,name=None)

TopKV2(values=<tf.Tensor: shape=(4, 1), dtype=float16, numpy=
array([[2.],
       [5.],
       [6.],
       [8.]], dtype=float16)>, indices=<tf.Tensor: shape=(4, 1), dtype=int32, numpy=
array([[1],
       [1],
       [2],
       [2]], dtype=int32)>)

In [28]:
tensor_two_d = tf.constant([[1,2,0],
                            [3,5,-1],
                            [1,5,6],
                            [2,3,8]],dtype=tf.float16)

tf.math.top_k(tensor_two_d,k=2,sorted=True,name=None)

TopKV2(values=<tf.Tensor: shape=(4, 2), dtype=float16, numpy=
array([[2., 1.],
       [5., 3.],
       [6., 5.],
       [8., 3.]], dtype=float16)>, indices=<tf.Tensor: shape=(4, 2), dtype=int32, numpy=
array([[1, 0],
       [1, 0],
       [2, 1],
       [2, 1]], dtype=int32)>)