<a href="https://colab.research.google.com/github/MohneetKaur/Computer-Vision-with-Python-and-Tensorflow/blob/main/Sparse_Tensor.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [1]:
import tensorflow as tf

Dense tensors store every element in a multi-dimensional array, making them suitable for data with a significant number of non-zero values,
albeit consuming more memory. Sparse tensors, however, represent data by only storing non-zero elements and their indices, which is efficient
for datasets with a majority of zeros or default values, leading to memory savings.

In [2]:
# Sparse Tensor

tensor_sparse = tf.sparse.SparseTensor(
    indices=[[0, 0], [1, 2]], values=[22, 77], dense_shape=[3, 4]
    )

print(tensor_sparse)

SparseTensor(indices=tf.Tensor(
[[0 0]
 [1 2]], shape=(2, 2), dtype=int64), values=tf.Tensor([22 77], shape=(2,), dtype=int32), dense_shape=tf.Tensor([3 4], shape=(2,), dtype=int64))


In [3]:
tf.sparse.to_dense(tensor_sparse)

<tf.Tensor: shape=(3, 4), dtype=int32, numpy=
array([[22,  0,  0,  0],
       [ 0,  0, 77,  0],
       [ 0,  0,  0,  0]], dtype=int32)>

In [4]:
st = tf.sparse.SparseTensor(
  indices=[[0, 0], [1, 2]], values=[1, 2], dense_shape=[3, 4])
st.set_shape([3, 4])

In [6]:
st.set_shape([3, None]) # Passing a None in the new shape allows any value for that axis

In [7]:
st.set_shape([1, 4]) # An error is raised if an incompatible shape is passed.

ValueError: Shapes (3, 4) and (1, 4) are not compatible

In [8]:
st = tf.sparse.from_dense([[1, 0, 2, 0], [3, 0, 0, 4]])
tf.sparse.to_dense(st.with_values([10, 20, 30, 40]))  # 4 nonzero values


<tf.Tensor: shape=(2, 4), dtype=int32, numpy=
array([[10,  0, 20,  0],
       [30,  0,  0, 40]], dtype=int32)>