<a href="https://colab.research.google.com/github/MohneetKaur/Computer-Vision-with-Python-and-Tensorflow/blob/main/String_Tensors.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [1]:
 import tensorflow as tf

In [2]:
tensor_string = tf.constant(["hello","i am","a string"])
print(tensor_string)

tf.Tensor([b'hello' b'i am' b'a string'], shape=(3,), dtype=string)


In [3]:
# as_string() function

tf.strings.as_string([3, 2])

<tf.Tensor: shape=(2,), dtype=string, numpy=array([b'3', b'2'], dtype=object)>

In [4]:
tf.strings.as_string([3.1415926, 2.71828], precision=2).numpy()

array([b'3.14', b'2.72'], dtype=object)

In [5]:
# bytes_split() function

tf.strings.bytes_split('hello').numpy()

array([b'h', b'e', b'l', b'l', b'o'], dtype=object)

In [6]:
tf.strings.bytes_split(['hello', '123'])

<tf.RaggedTensor [[b'h', b'e', b'l', b'l', b'o'], [b'1', b'2', b'3']]>

In [7]:
# format() function

tensor_a = tf.range(2)
tensor_b = tf.range(1, 4, 2)
tf.strings.format("a: {}, b: {}, suffix", (tensor_a, tensor_b))

<tf.Tensor: shape=(), dtype=string, numpy=b'a: [0 1], b: [1 3], suffix'>

In [8]:
# join() function

tf.strings.join(['abc','def']).numpy()

b'abcdef'

In [9]:
tf.strings.join([['abc','123'],
                 ['def','456'],
                 ['ghi','789']]).numpy()

array([b'abcdefghi', b'123456789'], dtype=object)

In [10]:
tf.strings.join([['abc','123'],
                 ['def','456']],
                 separator=" ").numpy()

array([b'abc def', b'123 456'], dtype=object)

In [11]:
# length() function

strings = tf.constant(['Hello','TensorFlow', '\U0001F642'])
tf.strings.length(strings).numpy() # default counts bytes

array([ 5, 10,  4], dtype=int32)

In [12]:
# lower() function

tf.strings.lower("CamelCase string and ALL CAPS")

<tf.Tensor: shape=(), dtype=string, numpy=b'camelcase string and all caps'>

In [13]:
# ngrams() function

tf.strings.ngrams(["A", "B", "C", "D"], 2).numpy()

array([b'A B', b'B C', b'C D'], dtype=object)

In [14]:
tf.strings.ngrams(["TF", "and", "keras"], 1).numpy()

array([b'TF', b'and', b'keras'], dtype=object)

In [15]:
# reduce_join() function

tf.strings.reduce_join([['abc','123'],
                        ['def','456']]).numpy()

b'abc123def456'

In [16]:
tf.strings.reduce_join([['abc','123'],
                        ['def','456']], axis=-1).numpy()

array([b'abc123', b'def456'], dtype=object)

In [17]:
tf.strings.reduce_join([['abc','123'],
                        ['def','456']],
                       axis=-1,
                       separator=" ").numpy()

array([b'abc 123', b'def 456'], dtype=object)

In [18]:
# regex_full_match() function

tf.strings.regex_full_match(["TF lib", "lib TF"], ".*lib$")

<tf.Tensor: shape=(2,), dtype=bool, numpy=array([ True, False])>

In [19]:
tf.strings.regex_full_match(["TF lib", "lib TF"], ".*TF$")

<tf.Tensor: shape=(2,), dtype=bool, numpy=array([False,  True])>



*   $	- at end of text (like \z not \Z) or line (m=true)
*   x*	- zero or more x, prefer more
* . -  any character, possibly including newline (s=true)





In [20]:
# regex_replace() function

tf.strings.regex_replace("Text with tags.<br /><b>contains html</b>",
                         "<[^>]+>", " ")

<tf.Tensor: shape=(), dtype=string, numpy=b'Text with tags.  contains html '>

In [21]:
# split() function

tf.strings.split('hello world').numpy()

array([b'hello', b'world'], dtype=object)

In [22]:
tf.strings.split(['hello world', 'a b c'])

<tf.RaggedTensor [[b'hello', b'world'], [b'a', b'b', b'c']]>

In [23]:
# strip() function

tf.strings.strip(["\nTensorFlow", "     The python library    "]).numpy()

array([b'TensorFlow', b'The python library'], dtype=object)

In [24]:
# substr() function

input = [b'Hello', b'World']
position = 1
length = 3

tf.strings.substr(
    input, pos=position, len=length, unit='BYTE', name=None
)

<tf.Tensor: shape=(2,), dtype=string, numpy=array([b'ell', b'orl'], dtype=object)>

In [25]:
input = [[b'ten', b'eleven', b'twelve'],
         [b'thirteen', b'fourteen', b'fifteen'],
         [b'sixteen', b'seventeen', b'eighteen']]
position = [[1, 2, 3],
            [1, 2, 3],
            [1, 2, 3]]
length =   [[2, 3, 4],
            [4, 3, 2],
            [5, 5, 5]]

tf.strings.substr(
    input, pos=position, len=length, unit='BYTE', name=None
)

<tf.Tensor: shape=(3, 3), dtype=string, numpy=
array([[b'en', b'eve', b'lve'],
       [b'hirt', b'urt', b'te'],
       [b'ixtee', b'vente', b'hteen']], dtype=object)>

In [26]:
input = [[b'ten', b'eleven', b'twelve'],
         [b'thirteen', b'fourteen', b'fifteen'],
         [b'sixteen', b'seventeen', b'eighteen'],
         [b'nineteen', b'twenty', b'twentyone']]
position = [1, 2, 3]
length =   [1, 2, 3]

tf.strings.substr(
    input, pos=position, len=length, unit='BYTE', name=None
)

<tf.Tensor: shape=(4, 3), dtype=string, numpy=
array([[b'e', b'ev', b'lve'],
       [b'h', b'ur', b'tee'],
       [b'i', b've', b'hte'],
       [b'i', b'en', b'nty']], dtype=object)>

In [27]:
input = b'thirteen'
position = [1, 5, 7]
length =   [3, 2, 1]

tf.strings.substr(
    input, pos=position, len=length, unit='BYTE', name=None
)

<tf.Tensor: shape=(3,), dtype=string, numpy=array([b'hir', b'ee', b'n'], dtype=object)>

In [29]:
# upper() function

tf.strings.upper("CamelCase string and ALL CAPS")

<tf.Tensor: shape=(), dtype=string, numpy=b'CAMELCASE STRING AND ALL CAPS'>

In [30]:
# to_number() function

tf.strings.to_number("3", tf.int32)

<tf.Tensor: shape=(), dtype=int32, numpy=3>